################################################################
####         TRex nightly test configuration file          ####
################################################################


### TRex configuration:
# hostname       - can be DNS name or IP for the TRex machine for ssh to the box
# password       - root password for TRex machine
# is_dual        - should the TRex inject with -p ?
# version_path   - path to the TRex version and executable
# cores          - how many cores should be used
# latency        - rate of latency packets injected by the TRex

### Router configuration:
# hostname       - the router hostname as apears in ______# cli prefix
# ip_address     - the router's ip that can be used to communicate with
# image          - the desired imaged wished to be loaded as the router's running config
# line_password  - router password when access via Telent
# en_password    - router password when changing to "enable" mode
# interfaces     - an array of client-server pairs, representing the interfaces configurations of the router
# configurations - an array of configurations that could possibly loaded into the router during the test. 
#                  The "clean" configuration is a mandatory configuration the router will load with to run the basic test bench

### TFTP configuration:
# hostname       - the tftp hostname
# ip_address     - the tftp's ip address
# images_path    - the tftp's relative path in which the router's images are located

### Test_misc configuration:
# expected_bw    - the "golden" bandwidth (in Gbps) results planned on receiving from the test

trex:
  hostname       : hostname
  password       : root password
  version_path   : not used
  cores          : 1

router:
  model          : device model
  hostname       : device hostname
  ip_address     : device ip 
  image          : device image name
  line_password  : telnet pass
  en_password    : enable pass
  mgmt_interface : GigabitEthernet0/0/0
  clean_config   : path to clean_config file
  intf_masking   : 255.255.255.0
  ipv6_mask      : 64
  interfaces     :
    - client : 
        name          : GigabitEthernet0/0/1
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.1000.0000
      server : 
        name          : GigabitEthernet0/0/2
        src_mac_addr  : 0000.0002.0000
        dest_mac_addr : 0000.2000.0000
      vrf_name      :   null
    - client : 
        name          : GigabitEthernet0/0/3
        src_mac_addr  : 0000.0003.0000
        dest_mac_addr : 0000.3000.0000
      server : 
        name          : GigabitEthernet0/0/4
        src_mac_addr  : 0000.0004.0000
        dest_mac_addr : 0000.4000.0000
      vrf_name      : dup  
    

tftp:
  hostname       : tftp hostname
  ip_address     : tftp ip
  root_dir       : tftp root dir
  images_path    : path related to root dir
