name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cd ET2500/vpp-24.02/; export ASROUTER_NAME=octeon10
    - name: make
      run: make build-release
    - name: make pkg
      run: make pkg-deb
