---
name: C/C++ CI

on:
  push:
    branches: ["main", "release_v1.0"]
  pull_request:
    branches: ["main", "release_v1.0"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    env:
      ASROUTER_NAME: octeon10
    steps:
      - name: Update apt and install make
        run: |
          apt-get update
          apt-get install -y make gcc g++ sudo git \
          libnl-3-dev libnl-route-3-dev libnl-genl-3-dev libnl-xfrm-3-dev

      - name: checkout code
        uses: actions/checkout@v4

      - name: print env
        run: echo "currently $ASROUTER_NAME"

      - name: git
        working-directory: ./ET2500/vpp-24.02/
        run: |
          git init

      - name: install deps
        working-directory: ./ET2500/vpp-24.02/
        run: yes |
          make install-dep

      - name: make
        working-directory: ./ET2500/vpp-24.02/
        run: |
          make build-release
          make pkg-deb